use_frameworks!
platform :ios , '8.0'
target 'TTAImageBrowser_Example' do
  pod 'TTAImageBrowser', :path => '../'

  target 'TTAImageBrowser_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
