language: swift
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod repo update
 - pod install --project-directory=Example
script:
- xcodebuild test -workspace Example/TTAImageBrowser.xcworkspace -scheme TTAImageBrowser-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7'
#- pod lib lint
